.changeset/config.json
.changeset/happy-pens-watch.md
.github/workflows/release.yml
packages/ui/package.json

- #1 
changeset 세팅 완료했습니다. 정식 배포 전까지는 patch 업데이트 하면 될 것 같아요!
https://www.npmjs.com/package/@freemed-kit/ui
```bash
pnpm changeset
```
위 명령어 실행, 포함시킬 패키지 선택 - 버전 선택 - summary 작성 - 생성된 마크다운 확인 후 커밋하면 됩니다!
이후 main 브랜치로 올라가면 자동으로 배포 PR 생성(`release: version packages`), main 브랜치로 머지하면 npm에 배포돼요.

chore: changeset 설정

---

.changeset/tasty-meals-stare.md
apps/docs/stories/avatar.stories.tsx
packages/ui/components/avatar.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Avatar 컴포넌트 구현

---

.changeset/rotten-bikes-shop.md
apps/docs/stories/badge.stories.tsx
packages/ui/components/badge.tsx
packages/ui/index.tsx

feat(ui): Badge 컴포넌트 구현

---

.changeset/hip-ducks-walk.md
apps/docs/stories/table.stories.tsx
packages/ui/components/table.tsx
packages/ui/index.tsx

Table 컴포넌트 구현

---

.changeset/young-months-draw.md
apps/docs/stories/textarea.stories.tsx
packages/ui/components/label.tsx
packages/ui/components/textarea.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Textarea 컴포넌트 구현

---

.changeset/yellow-stingrays-juggle.md
apps/docs/stories/checkbox.stories.tsx
apps/docs/stories/textarea.stories.tsx
packages/ui/components/checkbox.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Checkbox 컴포넌트 구현

---

.changeset/tender-otters-report.md
apps/docs/.storybook/preview.ts
apps/docs/package.json
apps/docs/postcss.config.cjs
apps/docs/stories/scroll-area.stories.tsx
apps/docs/tailwind.config.js
apps/docs/vite.config.ts
packages/ui/components/scroll-area.tsx
packages/ui/index.tsx
packages/ui/package.json
packages/ui/postcss.config.js
packages/ui/tailwind.config.js
pnpm-lock.yaml

- #23 
1. ScrollArea 컴포넌트를 구현했습니다.
2. docs에 tailwind, postcss 설정했습니다. (ScrollArea 예시에 필요해서 여기서 작업했어요.)
✅ docs에서 tailwind 적용 시 prefix로 `tw-` 붙이면 됩니다! (ui와 동일)

feat(ui): ScrollArea 컴포넌트 구현

---

.changeset/odd-toes-play.md
apps/docs/package.json
apps/docs/stories/accordion.stories.tsx
apps/docs/stories/calendar.stories.tsx
packages/ui/components/accordion.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #30 
- Accordion 컴포넌트를 구현하였습니다.
- #31 에서 `useState` 사용 수정하였습니다.
- 스토리북의 `useState`를 불러와 사용하였습니다.
- 화살표 함수 대신 함수 표현식으로 사용하여 수정하였습니다.

feat(ui): Accordion 컴포넌트 구현

---

.changeset/sharp-swans-grow.md
apps/docs/stories/separator.stories.tsx
packages/ui/components/separator.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #26 
Separator 컴포넌트를 구현했습니다.

feat(ui): Separator 컴포넌트 구현

---

.changeset/strong-rivers-clap.md
apps/docs/stories/resizable.stories.tsx
packages/ui/components/resizable.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #21 
Resizable 컴포넌트를 구현했습니다.

feat(ui): Resizable 컴포넌트 구현

---

.changeset/curvy-numbers-sin.md
apps/docs/stories/select.stories.tsx
packages/ui/components/select.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Select 컴포넌트 구현

---

.changeset/smart-bats-tickle.md
apps/docs/stories/tooltip.stories.tsx
packages/ui/components/tooltip.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Tooltip 컴포넌트 구현

---

.changeset/funny-schools-rest.md
apps/docs/stories/popover.stories.tsx
packages/ui/components/popover.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Popover 컴포넌트 구현

---

.changeset/gorgeous-maps-allow.md
apps/docs/stories/sheet.stories.tsx
packages/ui/components/sheet.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Sheet 컴포넌트 구현

---

.changeset/rare-cameras-nail.md
apps/docs/stories/dialog.stories.tsx
packages/ui/components/dialog.tsx
packages/ui/index.tsx

feat(ui): Dialog 컴포넌트 구현

---

.changeset/short-zoos-accept.md
apps/docs/stories/dropdown-menu.stories.tsx
packages/ui/components/dropdown-menu.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #50 
DropdownMenu 컴포넌트를 구현했습니다.

feat(ui): DropdownMenu 컴포넌트 구현

---

.changeset/soft-cobras-invite.md
apps/docs/stories/button.stories.tsx
apps/docs/stories/tabs.stories.tsx
packages/ui/components/tabs.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Tabs 컴포넌트 구현

---

.changeset/slimy-months-wash.md
apps/docs/package.json
apps/docs/stories/command.stories.tsx
packages/eslint-config/storybook.js
packages/ui/components/command.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #5 
Command 컴포넌트를 구현했습니다.
💬 스토리북 eslint-config rule에 `'@typescript-eslint/no-shadow': 'off'` 추가했습니다.
스타일이 제대로 적용되지 않는데 이건 다른 컴포넌트에서도 발견되는 문제라.. 같이 해결해 볼게요!

feat(ui): Command 컴포넌트 구현

---

.changeset/olive-keys-sparkle.md
apps/docs/stories/alert-dialog.stories.tsx
apps/docs/stories/dialog.stories.tsx
packages/ui/components/alert-dialog.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #53 
- AlertDialog 컴포넌트를 구현하였습니다.
- Dialog 컴포넌트 다시 원래 문서로 수정해놨습니다.

feat(ui): AlertDialog 컴포넌트 구현

---

.changeset/fluffy-ads-double.md
apps/docs/stories/alert.stories.tsx
packages/ui/components/alert.tsx
packages/ui/index.tsx

feat(ui): Alert 컴포넌트 구현

---

.changeset/purple-years-scream.md
apps/docs/stories/toast.stories.tsx
packages/ui/components/toast.tsx
packages/ui/components/toaster.tsx
packages/ui/hooks/use-toast.ts
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

feat(ui): Toast 컴포넌트 구현

---

.changeset/wise-birds-wash.md
apps/docs/stories/sidebar.stories.tsx
apps/docs/stories/toast.stories.tsx
packages/ui/components/button.tsx
packages/ui/components/sheet.tsx
packages/ui/components/sidebar.tsx
packages/ui/hooks/use-mobile.tsx
packages/ui/index.tsx
packages/ui/styles/globals.css
packages/ui/tailwind.config.js

- #38 
- Sidebar 컴포넌트를 구현했습니다.
- Toaster export 추가, toast.stories.tsx import문 수정했습니다.

feat(ui): Sidebar 컴포넌트 구현

---

.changeset/ninety-guests-reply.md
packages/ui/styles/globals.css

- #61 
- 일부 색상 변수 수정했습니다.
- v1.0.0 배포를 위해 changeset 문서 추가했습니다 .

feat(ui): globals.css color 변수 수정

---

.changeset/brown-squids-eat.md
apps/docs/package.json
apps/docs/stories/form.stories.tsx
packages/eslint-config/storybook.js
packages/ui/components/form.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #65 
- Form 컴포넌트를 구현하였습니다.
- React v19.0.0 으로 업데이트 하였습니다.

feat(ui): Form 컴포넌트 구현

---

.changeset/lazy-pens-check.md
apps/docs/stories/input-otp.stories.tsx
packages/ui/components/input-otp.tsx
packages/ui/index.tsx
packages/ui/package.json
packages/ui/tailwind.config.js
pnpm-lock.yaml

feat(ui): InputOTP 컴포넌트 구현

---

.changeset/poor-foxes-heal.md
packages/ui/package.json
packages/ui/styles/globals.css
packages/ui/tailwind.config.js

- #71 
- Sidebar 색상 zinc -> slate로 변경을 위해 globals.css 수정
- ui 패키지 files 필드에 tailwind.config.js 추가했습니다.
💬 Sidebar 작업 브랜치에서 패키지 업데이트 할게요!

feat(ui): globals.css 변수 & package.json files 필드 수정

---

.changeset/eight-ligers-hear.md
packages/ui/index.tsx

- #74 
index.tsx에 useFormField export 추가했습니다.

feat(ui): useFormField export 추가

---

.changeset/cuddly-geckos-rhyme.md
apps/docs/stories/hover-card.stories.tsx
packages/ui/components/hover-card.tsx
packages/ui/index.tsx
packages/ui/package.json
pnpm-lock.yaml

- #77 
HoverCard 컴포넌트를 구현했습니다.

feat(ui): HoverCard 컴포넌트 구현

---

.changeset/cool-bobcats-travel.md
packages/ui/index.tsx

- #80 
index.tsx에 Toast 관련 컴포넌트, toast 함수 export 추가했습니다.

feat(ui): Toast 컴포넌트 및 toast 함수 export 추가
